# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.2
yarn_mappings = 1.20.2+build.4
fabric_loader_version = 0.18.4

# Mod Properties
mod_name = Anecdote
mod_version = 0.0.0+1.20.2
maven_group = com.github.futurefrost
archives_base_name = Anecdote

# Dependencies
fabric_api_version = 0.91.6+1.20.2
origins_version = v1.12.10
apoli_version = 2.11.11
calio_version = 1.13.3
reach_version = 2.4.0
frostedlib_version = 1.2.0+1.20.2
pehkui_version = 3.8.0+1.14.4-1.20.4
kanos_config_tag = 0.4.1
cardinal_components_version=5.3.0
dcwa_version = 4.1
xxl_packets = 1.0.4-1.20.x-fabric