# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings = 1.20.1+build.10
fabric_loader_version = 0.18.4

# Mod Properties
mod_name = Anecdote
mod_version = 0.2.0+1.20-1.20.1
maven_group = com.github.futurefrost
archives_base_name = Anecdote

# Dependencies
fabric_api_version = 0.92.7+1.20.1
origins_version = v1.10.0
apoli_version = 2.9.0
calio_version = 1.11.0
reach_version = 2.4.0
frostedlib_version = 1.2.0+1.20-1.20.1
pehkui_version = 3.8.0+1.14.4-1.20.4
kanos_config_tag = 0.4.1
cardinal_components_version=5.2.3
dcwa_version = 4.1